version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_DB: fast_food_produto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2023"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres-network

  fast-food:
    build: .
    ports:
      - "8094:8084"
    environment:
      JAVA_OPTS: -Ddatabase_url=postgres-compose -Ddatabase_user=postgres -Ddatabase_password=Postgres2023
    networks:
      - postgres-network
    depends_on:
      - postgres-compose

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres: